// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: sophy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalXpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DiscordId string `protobuf:"bytes,2,opt,name=discord_id,json=discordId,proto3" json:"discord_id,omitempty"`
}

func (x *GlobalXpRequest) Reset() {
	*x = GlobalXpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sophy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalXpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalXpRequest) ProtoMessage() {}

func (x *GlobalXpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sophy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalXpRequest.ProtoReflect.Descriptor instead.
func (*GlobalXpRequest) Descriptor() ([]byte, []int) {
	return file_sophy_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalXpRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GlobalXpRequest) GetDiscordId() string {
	if x != nil {
		return x.DiscordId
	}
	return ""
}

type GlobalXpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewLevel int32 `protobuf:"varint,1,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`
	LevelUp  bool  `protobuf:"varint,2,opt,name=level_up,json=levelUp,proto3" json:"level_up,omitempty"`
}

func (x *GlobalXpResponse) Reset() {
	*x = GlobalXpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sophy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalXpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalXpResponse) ProtoMessage() {}

func (x *GlobalXpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sophy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalXpResponse.ProtoReflect.Descriptor instead.
func (*GlobalXpResponse) Descriptor() ([]byte, []int) {
	return file_sophy_proto_rawDescGZIP(), []int{1}
}

func (x *GlobalXpResponse) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

func (x *GlobalXpResponse) GetLevelUp() bool {
	if x != nil {
		return x.LevelUp
	}
	return false
}

var File_sophy_proto protoreflect.FileDescriptor

var file_sophy_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x6f, 0x70, 0x68, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x6f, 0x70, 0x68, 0x79, 0x22, 0x46, 0x0a, 0x0f, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x58, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x10,
	0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x58, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x19, 0x0a,
	0x08, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x32, 0x4d, 0x0a, 0x05, 0x53, 0x6f, 0x70, 0x68,
	0x79, 0x12, 0x44, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65, 0x72, 0x47, 0x6c, 0x6f, 0x62,
	0x61, 0x6c, 0x58, 0x70, 0x12, 0x16, 0x2e, 0x73, 0x6f, 0x70, 0x68, 0x79, 0x2e, 0x47, 0x6c, 0x6f,
	0x62, 0x61, 0x6c, 0x58, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73,
	0x6f, 0x70, 0x68, 0x79, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x58, 0x70, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sophy_proto_rawDescOnce sync.Once
	file_sophy_proto_rawDescData = file_sophy_proto_rawDesc
)

func file_sophy_proto_rawDescGZIP() []byte {
	file_sophy_proto_rawDescOnce.Do(func() {
		file_sophy_proto_rawDescData = protoimpl.X.CompressGZIP(file_sophy_proto_rawDescData)
	})
	return file_sophy_proto_rawDescData
}

var file_sophy_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sophy_proto_goTypes = []interface{}{
	(*GlobalXpRequest)(nil),  // 0: sophy.GlobalXpRequest
	(*GlobalXpResponse)(nil), // 1: sophy.GlobalXpResponse
}
var file_sophy_proto_depIdxs = []int32{
	0, // 0: sophy.Sophy.AddUserGlobalXp:input_type -> sophy.GlobalXpRequest
	1, // 1: sophy.Sophy.AddUserGlobalXp:output_type -> sophy.GlobalXpResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sophy_proto_init() }
func file_sophy_proto_init() {
	if File_sophy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sophy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalXpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sophy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalXpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sophy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sophy_proto_goTypes,
		DependencyIndexes: file_sophy_proto_depIdxs,
		MessageInfos:      file_sophy_proto_msgTypes,
	}.Build()
	File_sophy_proto = out.File
	file_sophy_proto_rawDesc = nil
	file_sophy_proto_goTypes = nil
	file_sophy_proto_depIdxs = nil
}
