// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: sophy.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GlobalXpRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DiscordId string `protobuf:"bytes,2,opt,name=discord_id,json=discordId,proto3" json:"discord_id,omitempty"`
}

func (x *GlobalXpRequest) Reset() {
	*x = GlobalXpRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sophy_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalXpRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalXpRequest) ProtoMessage() {}

func (x *GlobalXpRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sophy_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalXpRequest.ProtoReflect.Descriptor instead.
func (*GlobalXpRequest) Descriptor() ([]byte, []int) {
	return file_sophy_proto_rawDescGZIP(), []int{0}
}

func (x *GlobalXpRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GlobalXpRequest) GetDiscordId() string {
	if x != nil {
		return x.DiscordId
	}
	return ""
}

type GlobalXpResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NewLevel int32 `protobuf:"varint,1,opt,name=new_level,json=newLevel,proto3" json:"new_level,omitempty"`
	LevelUp  bool  `protobuf:"varint,2,opt,name=level_up,json=levelUp,proto3" json:"level_up,omitempty"`
}

func (x *GlobalXpResponse) Reset() {
	*x = GlobalXpResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sophy_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GlobalXpResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GlobalXpResponse) ProtoMessage() {}

func (x *GlobalXpResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sophy_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GlobalXpResponse.ProtoReflect.Descriptor instead.
func (*GlobalXpResponse) Descriptor() ([]byte, []int) {
	return file_sophy_proto_rawDescGZIP(), []int{1}
}

func (x *GlobalXpResponse) GetNewLevel() int32 {
	if x != nil {
		return x.NewLevel
	}
	return 0
}

func (x *GlobalXpResponse) GetLevelUp() bool {
	if x != nil {
		return x.LevelUp
	}
	return false
}

type GuildConfigRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token     string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	DiscordId string `protobuf:"bytes,2,opt,name=discord_id,json=discordId,proto3" json:"discord_id,omitempty"`
}

func (x *GuildConfigRequest) Reset() {
	*x = GuildConfigRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sophy_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildConfigRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildConfigRequest) ProtoMessage() {}

func (x *GuildConfigRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sophy_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildConfigRequest.ProtoReflect.Descriptor instead.
func (*GuildConfigRequest) Descriptor() ([]byte, []int) {
	return file_sophy_proto_rawDescGZIP(), []int{2}
}

func (x *GuildConfigRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GuildConfigRequest) GetDiscordId() string {
	if x != nil {
		return x.DiscordId
	}
	return ""
}

type GuildConfigResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LevelUpFormat string `protobuf:"bytes,1,opt,name=level_up_format,json=levelUpFormat,proto3" json:"level_up_format,omitempty"`
}

func (x *GuildConfigResponse) Reset() {
	*x = GuildConfigResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sophy_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GuildConfigResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GuildConfigResponse) ProtoMessage() {}

func (x *GuildConfigResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sophy_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GuildConfigResponse.ProtoReflect.Descriptor instead.
func (*GuildConfigResponse) Descriptor() ([]byte, []int) {
	return file_sophy_proto_rawDescGZIP(), []int{3}
}

func (x *GuildConfigResponse) GetLevelUpFormat() string {
	if x != nil {
		return x.LevelUpFormat
	}
	return ""
}

type SetGuildResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SetGuildResponse) Reset() {
	*x = SetGuildResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sophy_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetGuildResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGuildResponse) ProtoMessage() {}

func (x *SetGuildResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sophy_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGuildResponse.ProtoReflect.Descriptor instead.
func (*SetGuildResponse) Descriptor() ([]byte, []int) {
	return file_sophy_proto_rawDescGZIP(), []int{4}
}

type SetGuildLevelUpFormatRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *SetGuildLevelUpFormatRequest) Reset() {
	*x = SetGuildLevelUpFormatRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_sophy_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetGuildLevelUpFormatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetGuildLevelUpFormatRequest) ProtoMessage() {}

func (x *SetGuildLevelUpFormatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sophy_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetGuildLevelUpFormatRequest.ProtoReflect.Descriptor instead.
func (*SetGuildLevelUpFormatRequest) Descriptor() ([]byte, []int) {
	return file_sophy_proto_rawDescGZIP(), []int{5}
}

func (x *SetGuildLevelUpFormatRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_sophy_proto protoreflect.FileDescriptor

var file_sophy_proto_rawDesc = []byte{
	0x0a, 0x0b, 0x73, 0x6f, 0x70, 0x68, 0x79, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x73,
	0x6f, 0x70, 0x68, 0x79, 0x22, 0x46, 0x0a, 0x0f, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x58, 0x70,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a,
	0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x49, 0x64, 0x22, 0x4a, 0x0a, 0x10,
	0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x58, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x65, 0x77, 0x5f, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x6e, 0x65, 0x77, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x12, 0x19, 0x0a,
	0x08, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x5f, 0x75, 0x70, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x22, 0x49, 0x0a, 0x12, 0x47, 0x75, 0x69, 0x6c,
	0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1d, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72, 0x64, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x72,
	0x64, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x13, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x5f, 0x75, 0x70, 0x5f, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x46, 0x6f, 0x72, 0x6d,
	0x61, 0x74, 0x22, 0x12, 0x0a, 0x10, 0x53, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x34, 0x0a, 0x1c, 0x53, 0x65, 0x74, 0x47, 0x75, 0x69,
	0x6c, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x32, 0xf1, 0x01, 0x0a,
	0x05, 0x53, 0x6f, 0x70, 0x68, 0x79, 0x12, 0x44, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x55, 0x73, 0x65,
	0x72, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x58, 0x70, 0x12, 0x16, 0x2e, 0x73, 0x6f, 0x70, 0x68,
	0x79, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c, 0x58, 0x70, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x17, 0x2e, 0x73, 0x6f, 0x70, 0x68, 0x79, 0x2e, 0x47, 0x6c, 0x6f, 0x62, 0x61, 0x6c,
	0x58, 0x70, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x49, 0x0a, 0x0e,
	0x47, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x19,
	0x2e, 0x73, 0x6f, 0x70, 0x68, 0x79, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66,
	0x69, 0x67, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x73, 0x6f, 0x70, 0x68,
	0x79, 0x2e, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x57, 0x0a, 0x15, 0x53, 0x65, 0x74, 0x47, 0x75,
	0x69, 0x6c, 0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74,
	0x12, 0x23, 0x2e, 0x73, 0x6f, 0x70, 0x68, 0x79, 0x2e, 0x53, 0x65, 0x74, 0x47, 0x75, 0x69, 0x6c,
	0x64, 0x4c, 0x65, 0x76, 0x65, 0x6c, 0x55, 0x70, 0x46, 0x6f, 0x72, 0x6d, 0x61, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x17, 0x2e, 0x73, 0x6f, 0x70, 0x68, 0x79, 0x2e, 0x53, 0x65,
	0x74, 0x47, 0x75, 0x69, 0x6c, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00,
	0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sophy_proto_rawDescOnce sync.Once
	file_sophy_proto_rawDescData = file_sophy_proto_rawDesc
)

func file_sophy_proto_rawDescGZIP() []byte {
	file_sophy_proto_rawDescOnce.Do(func() {
		file_sophy_proto_rawDescData = protoimpl.X.CompressGZIP(file_sophy_proto_rawDescData)
	})
	return file_sophy_proto_rawDescData
}

var file_sophy_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_sophy_proto_goTypes = []interface{}{
	(*GlobalXpRequest)(nil),              // 0: sophy.GlobalXpRequest
	(*GlobalXpResponse)(nil),             // 1: sophy.GlobalXpResponse
	(*GuildConfigRequest)(nil),           // 2: sophy.GuildConfigRequest
	(*GuildConfigResponse)(nil),          // 3: sophy.GuildConfigResponse
	(*SetGuildResponse)(nil),             // 4: sophy.SetGuildResponse
	(*SetGuildLevelUpFormatRequest)(nil), // 5: sophy.SetGuildLevelUpFormatRequest
}
var file_sophy_proto_depIdxs = []int32{
	0, // 0: sophy.Sophy.AddUserGlobalXp:input_type -> sophy.GlobalXpRequest
	2, // 1: sophy.Sophy.GetGuildConfig:input_type -> sophy.GuildConfigRequest
	5, // 2: sophy.Sophy.SetGuildLevelUpFormat:input_type -> sophy.SetGuildLevelUpFormatRequest
	1, // 3: sophy.Sophy.AddUserGlobalXp:output_type -> sophy.GlobalXpResponse
	3, // 4: sophy.Sophy.GetGuildConfig:output_type -> sophy.GuildConfigResponse
	4, // 5: sophy.Sophy.SetGuildLevelUpFormat:output_type -> sophy.SetGuildResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sophy_proto_init() }
func file_sophy_proto_init() {
	if File_sophy_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_sophy_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalXpRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sophy_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GlobalXpResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sophy_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildConfigRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sophy_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GuildConfigResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sophy_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetGuildResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_sophy_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetGuildLevelUpFormatRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sophy_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sophy_proto_goTypes,
		DependencyIndexes: file_sophy_proto_depIdxs,
		MessageInfos:      file_sophy_proto_msgTypes,
	}.Build()
	File_sophy_proto = out.File
	file_sophy_proto_rawDesc = nil
	file_sophy_proto_goTypes = nil
	file_sophy_proto_depIdxs = nil
}
