[package]
name = "sophy_bot"
version = "0.1.0"
authors = ["Gabriel-Paulucci <gabrielpauluccimunizmendes@gmail.com>"]
edition = "2021"

# Dependencies

[dependencies]
dotenv = "0.15.0"
lazy_static = "1.4.0"
log = "0.4.14"
env_logger = "0.9.0"
chrono = "0.4.19"
clap = "3.0.0-beta.4"
image = "0.23.14"
imageproc = "0.22.0"
serde = "1.0.133"

[dependencies.serenity]
version = "0.10.9"
default-features = false
features = ["client", "gateway", "rustls_backend", "model", "unstable_discord_api"]

[dependencies.tokio]
version = "1.12.0"
features = ["macros", "rt-multi-thread", "parking_lot"]

[dependencies.sea-orm]
version = "0.4.2"
default-features = false
features = ["macros", "sqlx-postgres", "runtime-tokio-native-tls", "with-uuid"]

[dependencies.figment]
version = "0.10.6"
features = ["env", "toml"]

# Scripts

# prisma migrate dev --skip-generate
# sea-orm-cli generate entity -o src/database/entity
