[package]
name = "sophy_bot"
version = "0.1.0"
authors = ["Gabriel-Paulucci <gabrielpauluccimunizmendes@gmail.com>"]
edition = "2018"
resolver = "2"

# Dependencies

[dependencies]
dotenv = "0.15.0"
lazy_static = "1.4.0"
log = "0.4.14"
env_logger = "0.9.0"
chrono = "0.4.19"
clap = "3.0.0-beta.4"
image = "0.23.14"
imageproc = "0.22.0"

[dependencies.serenity]
version = "0.10.9"
default-features = false
features = ["client", "gateway", "rustls_backend", "model", "unstable_discord_api"]

[dependencies.tokio]
version = "1.12.0"
features = ["macros", "rt-multi-thread"]

[dependencies.rbatis]
version = "2.1.5"
default-features = false
features = ["postgres"]

[dependencies.refinery]
version = "0.7.0"
features = ["postgres"]

[dependencies.sqlx]
version = "0.5.9"
default-features = false
features = ["postgres", "runtime-async-std-rustls"]
