version: '3.9'

services:
  database:
    image: postgres:14-alpine3.15
    restart: always
    environment:
      POSTGRES_PASSWORD: ${APP_DATABASE_PASSWORD}
      POSTGRES_DB: sophy
    volumes:
      - database:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  bot:
    image: ghcr.io/fardragi/sophy/bot:in-dev
    restart: always
    depends_on:
      - server
    environment:
      - SOPHY_TOKEN=${APP_BOT_TOKEN}
      - SOPHY_GRPC_URL=http://server:6000

  server:
    image: ghcr.io/fardragi/sophy/server:in-dev
    restart: always
    depends_on:
      database:
        condition: service_healthy
    environment:
      - APP_GRPC_PORT=6000
      - APP_DATABASE_URL=postgres://postgres:${APP_DATABASE_PASSWORD}@database:5432/sophy

volumes:
  database:
