name: Api

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'api/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'api/**'

env:
  WORKING_DIR: ./api

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '^1.17.7'
    - run: go version

    - name: Tidy
      run: go mod tidy
      working-directory: ${{env.WORKING_DIR}}

    - name: Build
      run: go build
      working-directory: ${{env.WORKING_DIR}}