name: Bot

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'bot/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'bot/**'

env:
  CARGO_TERM_COLOR: always
  WORKING_DIR: ./bot

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Build
      run: cargo build --verbose
      working-directory: ${{env.WORKING_DIR}}

  clippy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Clippy
      run: cargo clippy --verbose
      working-directory: ${{env.WORKING_DIR}}
