name: Rust

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]

env:
  CARGO_TERM_COLOR: always

jobs:
  cache:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

  build:

    runs-on: ubuntu-latest
    needs: cache

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose

  clippy:

    runs-on: ubuntu-latest
    needs: cache

    steps:
    - uses: actions/checkout@v2
    - name: Clippy
      run: cargo clippy --verbose
