name: Server

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths:
      - 'server/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'server/**'

env:
  WORKING_DIR: ./web

jobs:
  build:
    runs_on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Build
      run: go build -v
      working-directory: ${{env.WORKING_DIR}}
