# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Web

on:
  workflow_dispatch:
  push:
    branches: [ master ]
    paths: 
      - 'web/**'
  pull_request:
    branches: [ master ]
    paths: 
      - 'web/**'
      
env:
  WORKING_DIR: ./web

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'yarn'
        
    - name: Install
    - run: yarn
    - working-directory: ${{env.WORKING_DIR}}

    - name: Build
    - run: yarn build
    - working-directory: ${{env.WORKING_DIR}}
